# Generated by Django 2.1.15 on 2020-11-24 09:57

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('hide', models.BooleanField(default=False)),
                ('color', colorfield.fields.ColorField(default='#0000FF', max_length=18)),
                ('status', models.CharField(choices=[('todo', 'TODO'), ('done', 'DONE'), ('none', 'NONE')], default='none', max_length=4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventsConnectedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_connected_users', to='calendars.Events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_connected_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Connected User',
                'verbose_name_plural': 'Event Connected Users',
            },
        ),
        migrations.CreateModel(
            name='EventsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Events Types',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendars.EventsTypes'),
        ),
        migrations.AlterUniqueTogether(
            name='eventsconnectedusers',
            unique_together={('user', 'event')},
        ),
    ]
