# Generated by Django 2.1.15 on 2020-12-12 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_add_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsconnectedusers',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_connected_users', to='calendars.Events'),
        ),
        migrations.AlterField(
            model_name='eventsconnectedusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_connected_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
