# Generated by Django 2.1.15 on 2020-07-03 10:22

import core.backends.azure_storage
from django.db import migrations, models
import django.db.models.deletion
import linked_files.utils.linked_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(storage=core.backends.azure_storage.AzureMediaStorage(), upload_to=linked_files.utils.linked_file.create_lined_file_path)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Linked File',
                'verbose_name_plural': 'Linked Files',
            },
        ),
    ]
