# Generated by Django 2.1.15 on 2020-11-18 19:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('done', 'DONE'), ('closed', 'CLOSED'), ('todo', 'TODO')], default='todo', max_length=6)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_reports', to='players.Player')),
            ],
            options={
                'verbose_name': 'Player Report',
                'verbose_name_plural': 'Player Reports',
            },
        ),
        migrations.CreateModel(
            name='PlayerReportProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('player_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_report_profiles', to='reports.PlayerReport')),
            ],
            options={
                'verbose_name': 'Player Report Profile',
                'verbose_name_plural': 'Player Report Profiles',
            },
        ),
        migrations.CreateModel(
            name='PlayerReportProfileStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_report_profile_statistics', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Player Report Profile Statistics',
                'verbose_name_plural': 'Player Report Profile Statistics',
            },
        ),
        migrations.CreateModel(
            name='PlayerReportProfileStatisticsGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_report_profile_statistics_groups', to='reports.PlayerReportProfiles')),
            ],
            options={
                'verbose_name': 'Player Report Profile Statistics Group',
                'verbose_name_plural': 'Player Report Profile Statistics Groups',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('open_date', models.DateTimeField(default=datetime.datetime.now)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('type', models.CharField(choices=[('test', 'TEST'), ('scouting', 'SCOUTING')], default='scouting', max_length=8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='ReportPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('editor', 'EDITOR'), ('viewer', 'VIEWER')], max_length=30)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_permissions', to='reports.Report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Permission',
                'verbose_name_plural': 'Report Permissions',
            },
        ),
        migrations.AddField(
            model_name='playerreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_reports', to='reports.Report'),
        ),
        migrations.AlterUniqueTogether(
            name='playerreportprofilestatisticsgroups',
            unique_together={('name', 'profile')},
        ),
        migrations.AlterUniqueTogether(
            name='playerreportprofilestatistics',
            unique_together={('name', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='playerreportprofiles',
            unique_together={('name', 'player_report')},
        ),
    ]
