# Generated by Django 2.1.15 on 2020-11-24 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerreportprofiles',
            name='player_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='reports.PlayerReport'),
        ),
        migrations.AlterField(
            model_name='playerreportprofilestatistics',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='playerreportprofilestatisticsgroups',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='reports.PlayerReportProfiles'),
        ),
        migrations.AlterField(
            model_name='reportpermission',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='reports.Report'),
        ),
        migrations.AlterField(
            model_name='reportpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
