# Generated by Django 2.1.15 on 2020-12-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20201124_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerreport',
            name='rating',
        ),
    ]
