# Generated by Django 2.1.15 on 2020-12-25 08:43

import core.backends.azure_storage
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import players.utils.invitation
import players.utils.invitation_template


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_file', models.FileField(storage=core.backends.azure_storage.AzureMediaStorage(), upload_to=players.utils.invitation.create_invitation_file_path)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
            },
        ),
        migrations.CreateModel(
            name='InvitationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('template', models.FileField(storage=core.backends.azure_storage.AzureMediaStorage(), upload_to=players.utils.invitation_template.create_invitation_template_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])])),
            ],
            options={
                'verbose_name': 'Invitation Template',
                'verbose_name_plural': 'Invitation Templates',
            },
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitation_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='players.InvitationTemplate'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='players.Player'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
