# Generated by Django 2.1.15 on 2021-01-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('goalkeeper 1', 'GOALKEEPER 1'), ('side defender 2', 'SIDE DEFENDER 2'), ('side defender 3', 'SIDE DEFENDER 3'), ('central defender 4', 'CENTRAL DEFENDER 4'), ('central defender 5', 'CENTRAL DEFENDER 5'), ('defensive help 6', 'DEFENSIVE HELP 6'), ('middle help 8', 'MIDDLE HELP 8'), ('middle help 10', 'MIDDLE HELP 10'), ('side help 7', 'SIDE HELP 7'), ('side help 11', 'SIDE HELP 11'), ('attacker 9', 'ATTACKER 9')], max_length=18),
        ),
    ]
